# Generated by Django 3.0.5 on 2020-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200701_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableuser',
            name='table_user_col_lastloginIP',
            field=models.CharField(db_column='Table_User_col_LastLoginIP', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tableuser',
            name='table_user_col_lastlogintime',
            field=models.DateTimeField(db_column='Table_User_col_LastLoginTime', null=True),
        ),
    ]
