# Generated by Django 3.0.5 on 2020-07-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200703_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_create_time',
        ),
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_modify_time',
        ),
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_send_time',
        ),
    ]
