# Generated by Django 3.0.5 on 2020-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200703_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_name',
            field=models.CharField(db_column='Table_User_col_Name', max_length=30, unique=True),
        ),
    ]
