# Generated by Django 3.0.5 on 2020-07-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_auto_20200703_1432'),
        ('login', '0007_auto_20200724_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_organization_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='supervisor.TableOrganization'),
        ),
    ]
