# Generated by Django 3.0.5 on 2020-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200728_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_birth',
            field=models.CharField(db_column='Table_User_col_Birth', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_postcode',
            field=models.CharField(db_column='Table_User_col_Postcode', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_tel',
            field=models.CharField(db_column='Table_User_col_Tel', max_length=128, null=True),
        ),
    ]
