# Generated by Django 3.0.5 on 2020-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200728_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_address',
        ),
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_birth',
        ),
        migrations.RemoveField(
            model_name='tableuser',
            name='table_user_col_postcode',
        ),
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_title',
            field=models.CharField(db_column='Table_User_col_Title', max_length=128, null=True),
        ),
    ]
