# Generated by Django 3.0.5 on 2020-07-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200728_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableuser',
            old_name='table_user_col_organization_id',
            new_name='table_user_col_organization',
        ),
    ]
