# Generated by Django 3.0.5 on 2020-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200728_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_email',
            field=models.CharField(db_column='Table_User_col_Email', max_length=128, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='tableuser',
            name='table_user_col_mobile',
            field=models.CharField(db_column='Table_User_col_Mobile', max_length=128, unique=True),
        ),
    ]
