# Generated by Django 3.0.5 on 2020-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableQuestionContent',
            fields=[
                ('table_question_content_col_question_id', models.AutoField(db_column='Table_Question_Content_col_Question_id', primary_key=True, serialize=False)),
                ('table_question_content_col_question_type', models.IntegerField(db_column='Table_Question_Content_col_Question_type', null=True)),
                ('table_question_content_col_indicator_id', models.IntegerField(db_column='Table_Question_Content_col_Indicator_id', null=True)),
                ('table_question_content_col_question_number', models.IntegerField(db_column='Table_Question_Content_col_Question_number', null=True)),
                ('table_question_content_col_auto', models.CharField(db_column='Table_Question_Content_col_Auto', max_length=1, null=True)),
                ('table_question_content_col_marks', models.CharField(db_column='Table_Question_Content_col_Marks', max_length=50, null=True)),
                ('table_question_content_col_content', models.TextField(db_column='Table_Question_Content_col_Content', null=True)),
            ],
            options={
                'db_table': 'Table_Question_Content',
                'managed': True,
            },
        ),
    ]
