# Generated by Django 3.0.5 on 2020-07-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_tabletimeliner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletimeliner',
            options={'managed': True},
        ),
    ]
