# Generated by Django 3.0.5 on 2020-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20200717_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletimeliner',
            name='table_timeliner_col_end',
            field=models.CharField(db_column='Table_Timeliner_col_end', max_length=128),
        ),
        migrations.AlterField(
            model_name='tabletimeliner',
            name='table_timeliner_col_start',
            field=models.CharField(db_column='Table_Timeliner_col_start', max_length=128),
        ),
    ]
