# Generated by Django 3.0.5 on 2020-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20200717_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablequestioncontent',
            name='table_question_content_col_auto',
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_mark_scheme',
            field=models.CharField(db_column='Table_Question_Content_col_Mark_scheme', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_markmethod',
            field=models.CharField(db_column='Table_Question_Content_col_Markmethod', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_question_attachment',
            field=models.CharField(db_column='Table_Question_Content_col_Question_attachment', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_question_class',
            field=models.CharField(db_column='Table_Question_Content_col_Question_class', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_question_importanswer',
            field=models.CharField(db_column='Table_Question_Content_col_Question_Importanswer', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_question_required',
            field=models.CharField(db_column='Table_Question_Content_col_Question_required', max_length=256, null=True),
        ),
    ]
