# Generated by Django 3.1 on 2020-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20200810_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablequestioncontent',
            name='table_question_content_col_content',
            field=models.JSONField(db_column='Table_Question_Content_col_Content', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tablequestioncontent',
            name='table_question_content_col_mark_scheme',
            field=models.JSONField(db_column='Table_Question_Content_col_Mark_scheme', max_length=256, null=True),
        ),
    ]
