# Generated by Django 3.1 on 2020-10-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_tableorganization_table_organization_col_unicode'),
        ('administrator', '0012_tablequestioncontent_table_question_content_col_eval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablequestioncontent',
            name='table_question_content_col_eval',
        ),
        migrations.AddField(
            model_name='tablequestioncontent',
            name='table_question_content_col_evalname',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.tableevaluation'),
        ),
    ]
