# Generated by Django 3.1.3 on 2020-12-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_tableevaluationindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUploadFile',
            fields=[
                ('table_upload_file_id', models.AutoField(db_column='Table_Upload_File_col_id', primary_key=True, serialize=False)),
                ('table_upload_file_name', models.CharField(db_column='Table_Upload_File_col_name', max_length=128)),
                ('table_upload_file_time', models.CharField(db_column='Table_Upload_File_col_time', max_length=128)),
                ('table_upload_file_evaluation', models.CharField(db_column='Table_Upload_File_col_evaluation', max_length=128)),
                ('table_upload_file_timeliner', models.CharField(db_column='Table_Upload_File_col_timeliner', max_length=128)),
                ('table_upload_file_cover', models.CharField(db_column='Table_Upload_File_col_cover', max_length=128)),
            ],
            options={
                'db_table': 'Table_Upload_File',
                'managed': True,
            },
        ),
    ]
