# Generated by Django 3.1.2 on 2020-12-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_tableuploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_cover',
            new_name='table_upload_file_col_cover',
        ),
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_evaluation',
            new_name='table_upload_file_col_evaluation',
        ),
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_id',
            new_name='table_upload_file_col_id',
        ),
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_name',
            new_name='table_upload_file_col_name',
        ),
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_time',
            new_name='table_upload_file_col_time',
        ),
        migrations.RenameField(
            model_name='tableuploadfile',
            old_name='table_upload_file_timeliner',
            new_name='table_upload_file_col_timeliner',
        ),
    ]
