# Generated by Django 3.0.5 on 2020-07-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableEvaluation',
            fields=[
                ('table_evaluation_col_id', models.IntegerField(db_column='Table_Evaluation_col_id', primary_key=True, serialize=False)),
                ('table_evaluation_col_name', models.CharField(db_column='Table_Evaluation_col_Name', max_length=50)),
                ('table_evaluation_col_administrator', models.CharField(db_column='Table_Evaluation_col_Administrator', max_length=50)),
                ('table_evaluation_col_status', models.CharField(db_column='Table_Evaluation_col_Status', max_length=128)),
                ('table_evaluation_col_create_time', models.CharField(db_column='Table_Evaluation_col_Create_Time', max_length=100)),
                ('table_evaluation_col_finish_time', models.CharField(db_column='Table_Evaluation_col_Finish_Time', max_length=100)),
                ('table_evaluation_col_organization', models.CharField(db_column='Table_Evaluation_col_Organization', max_length=50)),
                ('table_evaluation_col_deliver', models.CharField(db_column='Table_Evaluation_col_Deliver', max_length=50, null=True)),
                ('table_evaluation_col_mark', models.CharField(db_column='Table_Evaluation_col_Mark', max_length=128, null=True)),
                ('table_organization_col_indicator_name', models.CharField(db_column='Table_Organization_col_Indicator_Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Table_Evaluation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TableOrganization',
            fields=[
                ('table_organization_col_id', models.IntegerField(db_column='Table_Organization_col_id', primary_key=True, serialize=False)),
                ('table_organization_col_name', models.CharField(db_column='Table_Organization_col_Name', max_length=100)),
                ('table_organization_col_address', models.CharField(db_column='Table_Organization_col_Address', max_length=100, null=True)),
                ('table_organization_col_postcode', models.CharField(db_column='Table_Organization_col_Postcode', max_length=20, null=True)),
                ('table_organization_col_field', models.CharField(blank=True, db_column='Table_Organization_col_Field', max_length=50, null=True)),
                ('table_organization_col_parent_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.TableOrganization', verbose_name='父机构')),
            ],
            options={
                'db_table': 'Table_Organization',
                'managed': True,
            },
        ),
    ]
