# Generated by Django 3.1 on 2020-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_auto_20200703_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorganization',
            name='table_organization_col_unicode',
            field=models.CharField(db_column='Table_Organization_col_Unicode', max_length=50, null=True),
        ),
    ]
